# DuckDB config reference:
config:
  send_anonymous_usage_stats: False
  use_colors: True

strava_transform:
  target: dev
  outputs:
    dev:
      type: duckdb
      schema: dbt_sandbox
      threads: 1
      path: "{{ env_var('DUCKDB_PATH') }}"
    
    prod:
      type: duckdb
      schema: analytics
      threads: 1
      path: "{{ env_var('DUCKDB_PATH') }}"